feat(general): broadcast when CRUD method fails
mybethel/angular-sails-socket pull request #5
Opened 2016-11-04 07:56 UTC by nadeemkhedr

Closes #4

2016-11-04 08:56 UTC, nadeemkhedr commented
The Failing is not related to the PR, it should been failing before

2016-11-04 15:20 UTC, Ignigena requested changes
This looks great! I just fixed the existing failing tests  and it looks like there are a couple ESLint issues in this PR that should be addressed before merging.

2016-11-04 15:20 UTC, Ignigena commented on src/sailsSocket.js
> +      $rootScope.$broadcast('sailsSocket:error', response, data);
For consistency can we have the broadcast order the parameters with `data` first and `response` second?

2016-11-07 02:12 UTC, nadeemkhedr commented
Done! updated some eslint config and fixed all lint issues

2016-11-07 02:13 UTC, nadeemkhedr commented on src/sailsSocket.js
> +            case 'destroyed': {
This is actually interesting, didn't know about it http://eslint.org/docs/rules/no-case-declarations

2016-11-07 02:17 UTC, nadeemkhedr commented
don't know why travis is failing, looks like it is looking at old code, fixed the lint issues there

2016-11-07 03:44 UTC, Ignigena approved these changes

2016-11-07 03:45 UTC, merged

2016-11-07 03:46 UTC, Ignigena commented
Thanks Nadeem 👍